### ISSUE TITLE
Role-based redirects

### ISSUE THREAD

**Issue by jdahdah** [jon-sully/gatsby-plugin-netlify-identity-gotrue-demo#1]
Hi! I'm trying to implement [Netlify role-based redirects](https://docs.netlify.com/security/secure-access-to-sites/role-based-access-control/#redirect-visitors-based-on-roles) in combination with this demo (which has been very helpful so far, so thank you!). The rules in `_redirects` look something like this:

```
/files/confidential.pdf  /files/confidential.pdf  200!  Role=specialuser
/files/*  /hidden-area/login/  401!
```

So far the upper rule doesn't seem to catch: a logged-in user falls back to the 401 error even though they are logged in and they fulfill the role. I suspect that this has to do with the fact that https://github.com/jon-sully/react-netlify-identity-gotrue doesn't write a `nf_jwt` cookie, just the `ni.user` object in localStorage. At least looking at the official https://github.com/netlify/netlify-identity-widget, that does seem to be the main difference and my understanding is that Netlify role-based access [requires this cookie](https://docs.netlify.com/security/secure-access-to-sites/role-based-access-control/#netlify-identity). I could be misunderstanding, though. I'm not sure how to proceed here, would you be able to point me in the right direction?

**Comment by jon-sully** [comment]
Hey! I haven't actually been around this project in quite a while, but just off the cuff, do you have a space between the `Redirect`, the `=`, and the `specialuser`? I don't think you'll want to have any spaces there

**Comment by jdahdah** [comment]
Thanks for your quick reply, @jon-sully! Sorry for the error above, that was just in my abstracted example (which I've now corrected). The live code is working fine. I noticed that when I manually copy the value of `access_token` from `ni.goTrueToken` (in localStorage) into a `nf_jwt` cookie, the redirects work as expected on Netlify. I think the only way to get it working is by having this cookie and the `netlify-identity-widget` example at https://identity.netlify.com makes a call to https://identity.netlify.com/.netlify/identity/token, which sets the `httpOnly` cookie. I could just read the localStorage and copy over the value on every page load but I think that might not be secure as it would lack the `httpOnly` flag, and it feels pretty messy.

**Comment by jon-sully** [comment]
Gotcha. Yeah I can't remember at the moment and am currently out on holiday but I felt like I had that working in this library! Surprised that it's not. Does the README of this repo mention anything about cookies or RBAC / redirects files?

**Comment by jdahdah** [comment]
@jon-sully I've since figured out that `netlify-identity-widget` sets the cookie by adding the `X-Use-Cookies: 1` header to the `POST` request that goes to the `.netlify/identity/token` endpoint. This sets a secure HttpOnly cookie with the same token as the localStorage `access_token`. It's possible to get the same behavior with `react-netlify-identity-gotrue` (and I later saw that someone at Netlify also [suggested](https://answers.netlify.com/t/gotrue-js-doesnt-set-a-cookie/52447/2) this approach). The cookie can then be deleted by hitting the `.netlify/identity/logout` endpoint.

> Does the README of this repo mention anything about cookies or RBAC / redirects files?

Nope, doesn't look like it, and `react-netlify-identity-gotrue` doesn't hit either of those endpoints. I'm starting to think that Netlify might have changed their general approach to use cookies instead of localStorage since you wrote your library. `netlify-identity-widget` only uses localStorage for the user object, and handles all auth via cookies, probably to enable RBAC and other server-side/edge features.

I'll try to submit a PR to https://github.com/jon-sully/react-netlify-identity-gotrue next week if there's interest on your end and depending on my workload. For now I've patched the local package via `patch-package` and it seems to be working, but it's currently a bit of a hybrid solution and it might be worth moving everything over to cookies. In any case, thanks for your time and enjoy your holiday!

**Comment by jon-sully** [comment]
Thanks for the research! I have this lurking feeling that I may have done this intentionally, actually. I can't really remember (couple years ago now) but I think I may have ultimately found / decided that RBAC via the `_redirects` engine was just unreliable and inconsistent, so I may have specifically chosen to not keep doubled state (both locally stored state and cookie-stored state) to enable it — instead building this library around the intention of using Identity-enabled _functions_ for all user-driven things. The kind of RBAC-for-static-assets-only granted by `_redirects`, IMO, isn't as helpful for application-level features that likely require logic in addition to simple role checks 🤔 

But then, I really don't remember this all that well! I just sort of remember feeling that way about RBAC redirects

**Comment by jon-sully** [comment]
Yeah I think authorized fetch was the primary point of this library stack:

https://github.com/jon-sully/react-netlify-identity-gotrue?tab=readme-ov-file#async-identityauthorizedfetchurl-options

**Comment by jdahdah** [comment]
Thanks for explaining your thinking behind it, that makes a lot of sense. I'm trying to gate access to confidential PDF files but even with cookies working I have now run into reliability issues as well. Sometimes the user role is just ignored and the file is presented regardless of role or even login status (deleted cookie). I'm not sure if this is some Edge caching issue or something else. That's a deal-breaker, of course, so I might need to go a different route entirely. Might get in touch with Netlify Support. Thanks again for your time, I'll close this issue for now.

**Comment by jon-sully** [comment]
No problem, and sorry you're running into those issues.

FWIW, depending on how large the PDF is, you could have a Function that responds with the actual binary PDF content as the response of the function call if the person is correctly authenticated and authorized. Just an idea!
